import { redirect } from "next/navigation";

/**
 * The portfolio/activity content that used to live here moved to
 * /training — "Virtual Stock Training" is now the home for the $100,000
 * practice account (see src/app/training/page.js). This redirect exists so
 * any existing bookmark, browser history entry, or external link to
 * /dashboard still lands somewhere real instead of a 404; every link
 * generated by the app itself (nav, hero CTA, post-login redirect) now
 * points straight to /training.
 */
export default function DashboardPage() {
  redirect("/training");
}
